#!/usr/bin/env php
<?php

require_once __DIR__.'/FrontendKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new FrontendKernel('dev', true);

$application = new Application($kernel);
$application->run();
